### DISCUSSION TITLE
Vitest Coverage Differs locally from Github Actions

### DISCUSSION THREAD

**Discussion by jperetzIL** [vitest-dev/vitest#4189] [General]
Hi,

I have been dealing with this issue for a bit and haven't found a solution or anything about it online. I have just moved to vite and vitest from CRA and Jest. While most things were straight forward and worked great - I ran into an issue with testing coverage.

Here is my Vite config File
```
export default defineConfig(() => {
  return {
    define: {
      'process.env': {},
    },
    resolve: {
      alias: {
        UI: path.resolve(__dirname, './src/UI'),
        features: path.resolve(__dirname, './src/features'),
        hooks: path.resolve(__dirname, './src/hooks'),
        context: path.resolve(__dirname, './src/context'),
        lib: path.resolve(__dirname, './src/lib'),
        store: path.resolve(__dirname, './src/store'),
        api: path.resolve(__dirname, './src/api'),
        'test-utils': path.resolve(__dirname, './src/test-utils'),
      },
    },
    server: {
      open: true,
      port: '3000',
    },
    build: {
      outDir: 'build',
    },
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: './tests/setup.js',
      coverage: {
        all: true,
        provider: 'istanbul', // or 'v8',
        reporter: ['text', 'json', 'html'],
        include: ['src/'],
        exclude: [
          'node_modules/',
          'src/stories/',
          'src/store/',
          'api/',
          'src/test-utils',
        ],
        thresholdAutoUpdate: true,
        lines: 29.16,
        functions: 26.03,
        branches: 23.08,
        statements: 28.93,
        cleanOnRerun: true,
      },
    },
    plugins: [react(), eslint(), svgr()],
  };
});
```

Currently when I run `vitest run --coverage` locally I receive the following coverage:

![Screenshot 2023-09-26 at 4 12 22 PM](https://github.com/vitest-dev/vitest/assets/125289712/6fd5b222-66a4-4c86-838e-97712f991cfa)

But then when I run the same test through a github action:

```
name: Tests

on:
  pull_request:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Modules
        run: npm install --legacy-peer-deps
      - name: Run Tests
        run: npm run test:coverage
        env:
          CI: true
```

I get this:
![Screenshot 2023-09-26 at 4 12 36 PM](https://github.com/vitest-dev/vitest/assets/125289712/4318d4fb-4b55-433d-b14b-d596ad350c82)

As you can see - the Branches coverage is off by .1% and causing it to fail. I tried this with v8 as well and it did the same thing, but by .4% instead.

Any thoughts on what I might be missing here?
