### DISCUSSION TITLE
Significant Discrepancy in Test Execution Time

### DISCUSSION THREAD

**Discussion by ThomasCode92** [vitest-dev/vitest#6340] [Q&A]
We have a code repository containing approximately 860 tests. When running these tests locally using the command `yarn test:ci`, they complete in about 30 seconds. However, when the same tests are executed in our CI pipeline (via Azure Pipelines), they take between 5 to 6 minutes to finish.

What could be causing this significant discrepancy in test execution time between the local environment and the CI pipeline?
Is there a way to speed up the test on the pipeline?

For context, the tests are run with the command `yarn test:ci`, which triggers the npm script `vitest --run`. Below is the relevant pipeline step and the configuration from `vite.config.ts`:

## Azure Pipeline Step
```yaml
- script: |
     echo "##vso[task.setvariable variable=executed;isOutput=true]Yes" #set variable executed to Yes
     yarn test:ci --coverage.enabled --coverage.all
  displayName: Yarn Test
  name: 'UnitTests'
```

## Configuration
```typescript
test: {
      globals: true,
      poolOptions: { threads: { singleThread: true } },
      environment: 'jsdom',
      globalSetup: './src/test/test-globals.ts',
      setupFiles: './src/test/setup.ts',
      reporters: ['default', 'junit'],
      outputFile: 'test-results/unit-junit-results.xml',
      coverage: {
        src: ['./src'],
        provider: 'v8',
        reporter: ['text', 'lcov']
      },
      exclude: [
        '**/node_modules/**',
        '**/dist/**',
        '**/e2e-tests/**',
        '**/.{idea,git,cache,output,temp}/**',
        '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,tsup,build}.config.*'
      ],
      clearMocks: true
    }
```
