### ISSUE TITLE
Vitest fails when load WASM on CI machine but work locally

### ISSUE THREAD

**Issue by paulocoutinhox** [vitest-dev/vitest#2743]
### Describe the bug

Hi,

I have this error when run vitest on github action:

```

 ❯ tests/unit/local-client.spec.ts  (4 tests) 116ms
stderr | unknown test
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792
Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792)

 ❯ tests/unit/proxy-client.spec.ts  (3 tests) 106ms
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792
stderr | unknown test
Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792)

 ❯ tests/unit/remote-client.spec.ts  (4 tests) 112ms
stderr | unknown test
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792
Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Exception> @+1792)

 ✓ tests/unit/pages.spec.ts  (1 test) 30ms

⎯⎯⎯⎯⎯⎯ Failed Suites 3 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/unit/local-client.spec.ts > LocalClient
 FAIL  tests/unit/proxy-client.spec.ts > ProxyClient
 FAIL  tests/unit/remote-client.spec.ts > RemoteClient
TypeError: Cannot read property 'V' of undefined
 ❯ Module.___trap ../../build/wasm/bin/xplpc.js:9:69652

 ❯ abort ../../build/wasm/bin/xplpc.js:9:7978
 ❯ ../../build/wasm/bin/xplpc.js:9:9936

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/3]⎯

 Test Files  3 failed | 1 passed (4)
      Tests  1 passed (12)
   Start at  22:24:41
   Duration  7.62s (transform 2.23s, setup 1.33s, collect 1.63s, tests 364ms)
```

But it works locally on my machine.

### Reproduction

Full log:
https://github.com/xplpc/xplpc/actions/runs/4000925677/jobs/6866624479#step:11:227

Reproduce:

```
git clone https://github.com/xplpc/xplpc.git -b "fix-exceptions"
cd xplpc
python3 xplpc.py wasm-build
python3 xplpc.py wasm-test
```

or 

```
git clone https://github.com/xplpc/xplpc.git -b "fix-exceptions"
cd xplpc
python3 xplpc.py wasm-build
cd wasm/sample
npm run test:unit
```

or if is not possible build the wasm module, you can download it (below url), unzip and copy the build folder to root folder of xplpc cloned folder:
https://www.dropbox.com/s/3iqxjbma0kwsccc/build-wasm-xplpc.zip?dl=1

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 216.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-vue: ^2.0.0 => 2.3.4 
    vite: ^2.7.2 => 2.9.15 
    vitest: ^0.28.1 => 0.28.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by paulocoutinhox** [comment]
Hi,

I solved the problem.

If anyone have this problem, check the node version. Mine is 14 because of install order on Github Action machine.

Im using this to install node:

```
- name: Install Node
  uses: actions/setup-node@v3
  with:
    node-version: '19'
    architecture: 'x64'
```

But the problem is when i install Emscripten, because it install a new version of node too (v.14), that override the previous install.

So instead of:

```
- name: Install Node
  uses: actions/setup-node@v3
  with:
    node-version: '19'
    architecture: 'x64'

- name: Install EMSDK
  uses: mymindstorm/setup-emsdk@v11
  with:
    version: "3.1.28"
```

I change to:

```
- name: Install EMSDK
  uses: mymindstorm/setup-emsdk@v11
  with:
    version: "3.1.28"

- name: Install Node
  uses: actions/setup-node@v3
  with:
    node-version: '19'
    architecture: 'x64'
```
