### ISSUE TITLE
When tests fail during github-action@v3 the step does not emit failure exit

### ISSUE THREAD

**Issue by christ47** [vitest-dev/vitest#3673]
### Describe the bug

When my test ail in GHA pipeline no error is emitted. I receive a green tick for the the action step despite not all test passing.

### Reproduction

Action.yml

```
name:` Upload OpenAPI Specification
description: Uploads OpenAPI specification to relevant place
inputs:

  aws-region:
    description: AWS region
    required: true
  aws-access-key-id:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-account-id:
    description: "AWS account ID"
    required: true
  environment:
    description: " Environment"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"

    - name: Install
      shell: bash
      run: yarn install

    - name: Build
      shell: bash
      run: yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/automation-gha-ci
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

    - name: Run System Tests
      shell: bash
      env:
        CI: "true"
        VITEST_SEGFAULT_RETRY: "5"
        ENVIRONMENT: ${{ inputs.environment }}
      run: yarn system-test

```

run_system_test.yml

```

name: Run Stage System test

on:
  workflow_dispatch:

jobs:
  run-system-test:
    runs-on: ubuntu-latest
    name: Systems Tests
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    env:
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.GLOBAL_JFROG_ARTIFACTORY_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Stage System Tests
        uses: ./.github/actions/system-tests
        with:
          environment: stage
          aws-account-id: xxxxxxxxx
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.3
  npmPackages:
    @vitest/ui: ^0.29.7 => 0.29.7 
    vitest: ^0.28.3 => 0.28.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
