### ISSUE TITLE
vite-node's `import.meta.hot.accept` does not work

### ISSUE THREAD

**Issue by lukadev-0** [vitest-dev/vitest#3817]
### Describe the bug

Any `import.meta.hot.accept` function will break HMR and the function passed to accept is never called.

I've figured out the cause of this bug by modifying the module in `node_modules` and adding some console logs, here is what I've found.

https://github.com/vitest-dev/vitest/blob/b7ce1959bd469b83c3b7035579b7583386503489/packages/vite-node/src/hmr/hmr.ts#L105-L114

The problem is within this function, the `mod` variable will always return undefined. This is because the `path` within the update is relative to the project root, so if your project is within `/home/me/my-project` and you had a file named `main.js` within that directory, the update's `path` property would be `/main.js`.

However, the `hotModulesMap`'s keys are added here:

https://github.com/vitest-dev/vitest/blob/b7ce1959bd469b83c3b7035579b7583386503489/packages/vite-node/src/hmr/hmr.ts#L248

The `ownerPath` parameter is given in the runner:

https://github.com/vitest-dev/vitest/blob/b7ce1959bd469b83c3b7035579b7583386503489/packages/vite-node/src/client.ts#L375

The `fsPath` is an absolute path to the file, prepended by `/@fs/`, which is different from the format given in the `Update` object, meaning that the `mod` variable will always be undefined, causing it to do an early return.

### Reproduction

https://github.com/lukadev-0/vite-node-hmr-bug

### System Info

```yaml
  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (4) x64 AMD Athlon 300GE with Radeon Vega Graphics
    Memory: 913.02 MB / 5.71 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
    pnpm: 8.6.5 - ~/.local/share/pnpm/pnpm
  Browsers:
    Brave Browser: 115.1.56.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
