### ISSUE TITLE
Browser mode throws "Failed to fetch dynamically imported module" errors on files from repo or sometimes even dependencies

### ISSUE THREAD

**Issue by Ked57** [vitest-dev/vitest#5477]
### Describe the bug

I'm in the process of comparing all of the test runners on a very basic vue 3 composition API + TS app. So i setup testing lib and a basic test, it worked. Then I tried to add @vitest/browser and updated vitest.config.ts to use playwright and chromium but vitest started errors like

> TypeError: Failed to fetch dynamically imported module: http://localhost:5174/UsersMY-USER/vue3-browser-testing/vitest-testing-lib.setup.ts?v=1712061179715
Or
> ReferenceError: Vue is not defined

### Reproduction

I haven't seen this error anywhere else but I reproduced it in StackBlitz, the setup is fairly similar to the one on my machine and gives the same result

https://stackblitz.com/edit/vitest-dev-vitest-urjsz7

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M2
    Memory: 94.95 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    pnpm: 8.15.3 - /opt/homebrew/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.3
  npmPackages:
    @vitejs/plugin-vue: ^4.6.2 => 4.6.2 
    @vitest/ui: ^1.4.0 => 1.4.0 
    vite: ^4.5.3 => 4.5.3 
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`@vue/test-utils` expects Vue to be defined on a global object (UMD) in its browser build for some reason. Try deduping Vue in the config instead:

```ts
export default {
  resolve: {
    dedupe: ['vue'],
  }
}
```

**Comment by Ked57** [comment]
it solves the Vue import issue and now it's another package. I updated the stackblitz

> TypeError: Failed to fetch dynamically imported module: https://vitestdevvitesturjsz7-5l23--5179--7dbe22a9.local-credentialless.webcontainer.io/home/projects/vitest-dev-vitest-urjsz7/test/Hello.spec.ts?browserv=0

**Comment by favna** [comment]
I'm also facing this issue but with importing `http://localhost:5173/@id/@vitest/coverage-v8/browser?import` and only in GitHub actions: https://github.com/sapphiredev/shapeshift/actions/runs/10980564537?pr=396. This is clearly not something I can influence, because it's a vitest library. I also get the same issue with coverage Istanbul as seen here: https://github.com/sapphiredev/shapeshift/actions/runs/10979357381/job/30483626781?pr=396.

I have no idea what I can do to resolve this.

**Comment by nickschaap** [comment]
I'm seeing the import issue `http://localhost:5173/@id/@vitest/coverage-v8/browser?import` on vitest 3.0.8 with v8 as my coverage provider

**Comment by Aquaticat** [comment]
I'm seeing the same issue.
```txt
❯ pnpm exec vitest
Testing types with tsc and vue-tsc is an experimental feature.
Breaking changes might not follow SemVer, please pin Vitest's version when using it.

 DEV  v3.2.3 C:/Users/user/Text/Projects/Aquaticat/monochromatic2025MAY24-pnpmTest
      API started at http://localhost:3001/
      Coverage enabled with v8
```

```txt
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 3 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Prepare Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Failed to fetch dynamically imported module: http://localhost:3003/@id/@vitest/coverage-v8/browser?import

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Run Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Failed to fetch dynamically imported module: http://localhost:3003/@id/@vitest/coverage-v8/browser?import

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Coverage Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Failed to fetch dynamically imported module: http://localhost:3003/@id/@vitest/coverage-v8/browser?import
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

package.json
```json
  "devDependencies": {
    "vitest": "catalog:",
    "vite": "catalog:",
    "@vitest/coverage-v8": "catalog:",
    "@vitest/browser": "catalog:",
    "@vitest/ui": "catalog:",
    "playwright": "catalog:",
```

pnpm-workspace.yaml
```yaml
packageExtensions:
  vite:
    peerDependencies:
      'strip-literal': '*'
      '@vitest/coverage-v8': '*'
  vitest:
    peerDependencies:
      '@vitest/coverage-v8': '>=3.2.3'
      '@vitest/browser': '>=3.2.3'
      'vite': '*'
      '@vitest/ui': '*'
      'playwright': '>=1.53.0'
    dependencies:
      'strip-literal': '>=3.0.0'
      # sugarss: '>=5.0.0'
  '@vitest/browser':
    peerDependencies:
      vite: '*'
      '@vitest/coverage-v8': '>=3.2.3'
  'vite-node':
    peerDependencies:
      vite: '*'
peerDependencyRules:
  allowedVersions:
    '@vitejs/plugin-basic-ssl>vite': '>=7.0.0-beta.1'
    'vite-plugin-singlefile>vite': '>=7.0.0-beta.1'
    'vite-plugin-json5>vite': '>=7.0.0-beta.1'
    '@vitest/browser>vite': '>=7.0.0-beta.1'
    '@vitest/mocker>vite': '*'
```
