### ISSUE TITLE
Vitest fails to import a private git+ssh package in pnpm but works in npm.

### ISSUE THREAD

**Issue by 0pengu** [vitest-dev/vitest#7047]
### Describe the bug

I've been trying to debug this for a couple hours now but to no avail. When I attempt to run vitest within the repository files, I get the following error:

```bash
Error: Failed to load url /Users/0pengu/Desktop/gh/parentlink/server/node_modules/.pnpm/@parentlink+sj@git+ssh+++git@github.com+parentlink+sj.git#c6d910bc2ecf49961b96b4fa45930f42831b5792/node_modules/@parentlink/sj/index.ts (resolved id: /Users/0pengu/Desktop/gh/parentlink/server/node_modules/.pnpm/@parentlink+sj@git+ssh+++git@github.com+parentlink+sj.git#c6d910bc2ecf49961b96b4fa45930f42831b5792/node_modules/@parentlink/sj/index.ts) in /Users/0pengu/Desktop/gh/parentlink/server/tests/auth/index.test.ts. Does the file exist?
```

I whittled the issue down to npm working properly in this case without any changes. Below is some relevant information:

Package.json
```json
{
  "name": "parentlink-server",
  "version": "1.0.0",
  "private": "true",
  "description": "ParentLink Server - Written in Express.js",
  "scripts": {
    "dev": "tsx --watch src/index.ts",
    "test": "vitest",
    "test:prod": "vitest run",
    "prestart": "prisma migrate deploy",
    "start": "tsx src/index.ts",
    "postinstall": "prisma generate",
    "lint": "eslint .",
    "db:pull": "prisma db pull",
    "db:migrate": "prisma migrate dev",
    "db:generate": "prisma generate",
    "db:prod": "prisma migrate deploy",
    "db:cp": "pnpm run db:generate && cp ./prisma/generated/zod/index.ts ../shared/types/db/generated/index.ts",
    "env:pull": "pnpx dotenv-vault@latest pull",
    "env:push": "pnpx dotenv-vault@latest push",
    "build": "docker build --build-arg GITHUB_TOKEN=\"$GITHUB_TOKEN\" -t parentlink/server ."
  },
  "license": "ISC",
  "dependencies": {
    "@lucia-auth/adapter-prisma": "^4.0.1",
    "@oslojs/crypto": "^1.0.1",
    "@oslojs/encoding": "^1.1.0",
    "@parentlink/attempt": "github:parentlink/attempt#main",
    "@parentlink/console-log": "github:parentlink/console-log#main",
    "@parentlink/format-number": "github:parentlink/format-number#main",
    "@parentlink/is-equal": "github:parentlink/is-equal#main",
    "@parentlink/sj": "github:parentlink/sj#main",
    "@parentlink/types": "github:parentlink/types#main",
    "@prisma/client": "5.22.0",
    "cookie-parser": "^1.4.7",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "dotenv-cli": "^7.4.4",
    "express": "^4.21.0",
    "hello": "^0.6.2",
    "lucia": "^3.2.2",
    "morgan": "^1.10.0",
    "nodemailer": "^6.9.16",
    "nodemon": "^3.1.7",
    "superjson": "^2.2.1",
    "vite-tsconfig-paths": "^5.1.4",
    "zod": "^3.23.8",
    "zod-prisma-types": "^3.1.8"
  },
  "devDependencies": {
    "@eslint/js": "^9",
    "@types/cookie-parser": "^1.4.8",
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.21",
    "@types/morgan": "^1.9.9",
    "@types/nodemailer": "^6.4.17",
    "@types/supertest": "^6.0.2",
    "eslint": "^8",
    "prisma": "^5.22.0",
    "supertest": "^7.0.0",
    "tsx": "^4.19.2",
    "typescript": "^5",
    "typescript-eslint": "^8",
    "vitest": "^2.1.8"
  }
}
```

pnpm-lock.yaml (only the git packages):
```yaml  '@parentlink/attempt@git+ssh://git@github.com/parentlink/attempt.git#3539e7017ee818be72c10ae4e8e02da76a5a44b2':
    resolution: {commit: 3539e7017ee818be72c10ae4e8e02da76a5a44b2, repo: git+ssh://git@github.com/parentlink/attempt.git, type: git}
    version: 1.0.0

  '@parentlink/console-log@git+ssh://git@github.com/parentlink/console-log.git#28ec7b8e16f43851fa46abd8ff578280120be110':
    resolution: {commit: 28ec7b8e16f43851fa46abd8ff578280120be110, repo: git+ssh://git@github.com/parentlink/console-log.git, type: git}
    version: 1.0.0

  '@parentlink/format-number@git+ssh://git@github.com/parentlink/format-number.git#fda45e21a1f0406b5e53a08ea772b55eaf62a212':
    resolution: {commit: fda45e21a1f0406b5e53a08ea772b55eaf62a212, repo: git+ssh://git@github.com/parentlink/format-number.git, type: git}
    version: 1.0.0

  '@parentlink/is-equal@git+ssh://git@github.com/parentlink/is-equal.git#bd2471c789bbe6bc886cbe9222e1fc5fa4684818':
    resolution: {commit: bd2471c789bbe6bc886cbe9222e1fc5fa4684818, repo: git+ssh://git@github.com/parentlink/is-equal.git, type: git}
    version: 1.0.0

  '@parentlink/sj@git+ssh://git@github.com/parentlink/sj.git#c6d910bc2ecf49961b96b4fa45930f42831b5792':
    resolution: {commit: c6d910bc2ecf49961b96b4fa45930f42831b5792, repo: git+ssh://git@github.com/parentlink/sj.git, type: git}
    version: 1.0.0

  '@parentlink/types@git+ssh://git@github.com/parentlink/types.git#5530d20be5dd40cf67eafe93b1872bd14374f9f6':
    resolution: {commit: 5530d20be5dd40cf67eafe93b1872bd14374f9f6, repo: git+ssh://git@github.com/parentlink/types.git, type: git}
    version: 1.0.0
```

tsconfig.json:
```json
{
    "compilerOptions": {
      "baseUrl": "./",
      "types": ["vitest/globals"],
      "allowJs": true,
      "skipLibCheck": true,
      "strict": true,
      "noEmit": true,
      "esModuleInterop": true,
      "resolveJsonModule": true,
      "paths": {
        "@/*": ["src/*"]
      }
    },
    "include": ["**/*.ts", "**/*.tsx", "src/lib/types/*.d.ts", "vitest.config.mts"],
    "exclude": ["node_modules"]
  }
  ```
  
  vitest.config.mts:
  ```ts
  import { defineConfig } from "vitest/config";
import path from "path";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    server: {
      deps: {
        inline: ["@parentlink/sj"],
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  plugins: [tsconfigPaths()],
});
```

### Reproduction

Clone the repo.

```bash
git clone https://github.com/0pengu/vitest-bug.git
```

Install packages with pnpm (vitest is preinstalled).

```bash
pnpm i
```

Test that vitest works before doing anything:

```bash
pnpm run test
```

You need to create a private Git repository that can be downloaded as a package.

Copy index.ts and put it on a private repo, along with a basic package.json (it has no dependencies)

```bash
cp index.ts /path/to/private/repo
cd /path/to/private/repo
pnpm init // BEFORE YOU MOVE ON, NAME YOUR PACKAGE WITH AN @. EX: @hello/add
git init
ECHO node_modules > .gitignore

git add .
git commit -am "Init"
git remote add origin <git-url>
git push
```

If you forgot, make sure the private repo's package name starts with an @.
The bug only works with private Git packages, the easiest way to download git packages is to just open your ~/.gitignore and enter the following:

```yml
[url "https://{YOUR-GITHUB-PAT-TOKEN-WITH-REPO-ACCESS-GOES-HERE}@github.com/"]
	insteadOf = git+ssh://git@github.com/
```

Replace the brackets with your PAT token.

Then simply run:

```bash
pnpm install username/reponame
```

Then, import the code into the index.test.ts file:

```ts
import { add } from @hello/add
```

You should observe an error.

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 68.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /usr/local/bin/npm
    pnpm: 9.14.4 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.109
    Edge: 126.0.2592.68
    Safari: 18.1.1
  npmPackages:
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
